// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ch_14_relations.Repositories;

#nullable disable

namespace ch_14_relations.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ch_14_relations.Entities.Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Price = 89.99m,
                            Title = "Suç ve Ceza"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Price = 79.50m,
                            Title = "Sefiller"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Price = 105.00m,
                            Title = "Zamanın Kısa Tarihi"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Price = 92.25m,
                            Title = "Kozmos"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Price = 65.00m,
                            Title = "Nutuk"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Price = 70.00m,
                            Title = "Medeniyetler Çatışması"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Price = 50.00m,
                            Title = "Devlet"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Price = 60.00m,
                            Title = "Varoluşçuluk"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Price = 110.00m,
                            Title = "Yapay Zeka 101"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Price = 95.00m,
                            Title = "Kodlama Mantığı"
                        });
                });

            modelBuilder.Entity("ch_14_relations.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Roman"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Bilim"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Tarih"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Felsefe"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Teknoloji"
                        });
                });

            modelBuilder.Entity("ch_14_relations.Entities.Book", b =>
                {
                    b.HasOne("ch_14_relations.Entities.Category", "Category")
                        .WithMany("Books")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ch_14_relations.Entities.Category", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
