// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ch_11_repo_in_use.Repositories;

#nullable disable

namespace ch_11_repo_in_use.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20250506140737_mig_01")]
    partial class mig_01
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Book", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Title")
                        .HasMaxLength(25)
                        .HasColumnType("varchar(25)");

                    b.HasKey("Id");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Price = 10m,
                            Title = "Book 1"
                        },
                        new
                        {
                            Id = 2,
                            Price = 20m,
                            Title = "Book 2"
                        },
                        new
                        {
                            Id = 3,
                            Price = 30m,
                            Title = "Book 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
